document.addEventListener("DOMContentLoaded", () => {
  const DEFAULT_PORT = 32145;
  const elements = {
    enabled: document.getElementById("agentBridgeEnabled"),
    port: document.getElementById("agentBridgePort"),
    token: document.getElementById("agentBridgeToken"),
    allowedOrigins: document.getElementById("agentBridgeAllowedOrigins"),
    save: document.getElementById("saveAgentBridgeBtn"),
    check: document.getElementById("checkAgentBridgeBtn"),
    toggleToken: document.getElementById("toggleTokenBtn"),
    status: document.getElementById("agentBridgeStatus"),
    statusIndicator: document.getElementById("statusIndicator"),
    version: document.getElementById("extensionVersion")
  };

  elements.version.textContent = chrome.runtime.getManifest().version;

  function setStatus(message, state = "idle") {
    elements.status.textContent = message;
    elements.statusIndicator.dataset.state = state;
  }

  function normalizeOrigins(value) {
    const origins = [];
    const seen = new Set();
    String(value || "").split(/[\n,]+/).forEach((entry) => {
      const text = entry.trim();
      if (!text) return;
      try {
        const parsed = new URL(text.includes("://") ? text : `https://${text}`);
        if (!["http:", "https:"].includes(parsed.protocol)) return;
        const origin = parsed.origin.toLowerCase();
        if (!seen.has(origin)) {
          seen.add(origin);
          origins.push(origin);
        }
      } catch (_error) {
        return;
      }
    });
    return origins;
  }

  function readForm() {
    const parsedPort = Number.parseInt(elements.port.value, 10);
    return {
      enabled: elements.enabled.checked,
      port: Number.isInteger(parsedPort) && parsedPort >= 1024 && parsedPort <= 65535
        ? parsedPort
        : DEFAULT_PORT,
      token: elements.token.value.trim(),
      allowedOrigins: normalizeOrigins(elements.allowedOrigins.value)
    };
  }

  function validate(config, requireEnabled = false) {
    if ((config.enabled || requireEnabled) && config.token.length < 32) {
      return "Enter the pairing token generated by the local AI Visit website plugin.";
    }
    if ((config.enabled || requireEnabled) && !config.allowedOrigins.length) {
      return "Add at least one authorized website origin.";
    }
    return null;
  }

  function loadSettings() {
    chrome.storage.local.get(
      {
        agentBridgeEnabled: false,
        agentBridgePort: DEFAULT_PORT,
        agentBridgeToken: "",
        agentBridgeAllowedOrigins: []
      },
      (stored) => {
        if (chrome.runtime.lastError) {
          setStatus("Chrome could not load the local bridge settings.", "error");
          return;
        }
        elements.enabled.checked = stored.agentBridgeEnabled === true;
        elements.port.value = String(stored.agentBridgePort || DEFAULT_PORT);
        elements.token.value = String(stored.agentBridgeToken || "");
        elements.allowedOrigins.value = normalizeOrigins(
          stored.agentBridgeAllowedOrigins
        ).join("\n");
        setStatus(
          elements.enabled.checked
            ? "Bridge configured. Check the local connection when the plugin is running."
            : "Bridge disabled. Add pairing details and enable it to accept agent tasks.",
          "idle"
        );
      }
    );
  }

  elements.save.addEventListener("click", () => {
    const config = readForm();
    const validationError = validate(config);
    if (validationError) {
      setStatus(validationError, "error");
      return;
    }

    chrome.storage.local.set(
      {
        agentBridgeEnabled: config.enabled,
        agentBridgePort: config.port,
        agentBridgeToken: config.token,
        agentBridgeAllowedOrigins: config.allowedOrigins
      },
      () => {
        if (chrome.runtime.lastError) {
          setStatus("Chrome could not save the local bridge settings.", "error");
          return;
        }
        chrome.runtime.sendMessage(
          { type: "agent-browser-bridge-config-changed", enabled: config.enabled },
          () => {
            void chrome.runtime.lastError;
            setStatus(
              config.enabled
                ? "Bridge settings saved. The extension is ready to claim agent tasks."
                : "Bridge disabled. No agent tasks will be claimed.",
              config.enabled ? "success" : "idle"
            );
          }
        );
      }
    );
  });

  elements.check.addEventListener("click", async () => {
    const config = readForm();
    const validationError = validate(config, true);
    if (validationError) {
      setStatus(validationError, "error");
      return;
    }

    setStatus("Checking the local bridge…", "checking");
    try {
      const response = await fetch(
        `http://127.0.0.1:${config.port}/v1/extension/heartbeat`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${config.token}`,
            "Content-Type": "application/json"
          },
          body: JSON.stringify({ extensionVersion: chrome.runtime.getManifest().version }),
          cache: "no-store",
          credentials: "omit"
        }
      );

      if (response.ok) {
        setStatus("Connected to the local AI Visit website bridge.", "success");
      } else if (response.status === 401) {
        setStatus("The local bridge rejected the pairing token.", "error");
      } else {
        setStatus(`The local bridge returned HTTP ${response.status}.`, "error");
      }
    } catch (_error) {
      setStatus("The local bridge is not reachable on this port.", "error");
    }
  });

  elements.toggleToken.addEventListener("click", () => {
    const reveal = elements.token.type === "password";
    elements.token.type = reveal ? "text" : "password";
    elements.toggleToken.textContent = reveal ? "Hide" : "Show";
    elements.toggleToken.setAttribute("aria-pressed", String(reveal));
  });

  loadSettings();
});
